import { getStore } from '@netlify/blobs';
import { createEngagementToken } from './_shared/engagement-token.mjs';
import { PORTAL_STORE, authorizeOperator, cleanText, getProject, json, listPortals, logActivity, normalizeEmail, randomHex, validPortalId, validProjectNumber } from './_shared/command-center-admin.mjs';
const RESEND_ENDPOINT='https://api.resend.com/emails';
export default async function handler(req){
  if(!authorizeOperator(req))return json({error:'Unauthorized.'},401);
  if(req.method==='GET'){const p=cleanText(new URL(req.url).searchParams.get('projectNumber'),80).toUpperCase();if(!validProjectNumber(p))return json({error:'Valid Project # required.'},400);return json({ok:true,portals:await listPortals(p)})}
  if(req.method==='POST')return createPortal(req);
  if(req.method==='PATCH')return updatePortal(req);
  return json({error:'Method not allowed.'},405,{Allow:'GET, POST, PATCH'});
}
async function createPortal(req){let b;try{b=await req.json()}catch{return json({error:'Invalid JSON request body.'},400)}const p=cleanText(b?.projectNumber,80).toUpperCase();if(!validProjectNumber(p))return json({error:'Valid Project # required.'},400);const project=await getProject(p);if(!project)return json({error:'Project not found.'},404);const email=normalizeEmail(b?.recipientEmail||project.email);if(!/^\S+@\S+\.\S+$/.test(email))return json({error:'Valid portal recipient email required.'},400);const configured=Number(process.env.CONVERA_PORTAL_DEFAULT_DAYS||30),days=Math.min(180,Math.max(1,Number(b?.expiresDays||configured||30))),expiresAt=new Date(Date.now()+days*86400000).toISOString();const portalId=`PRT-${p.split('-').pop()}-${randomHex(4)}`;const defaultVerify=String(process.env.CONVERA_PORTAL_REQUIRE_EMAIL_VERIFICATION||'true').toLowerCase()!=='false';const requireEmailVerification=b?.requireEmailVerification===undefined?defaultVerify:Boolean(b.requireEmailVerification);const now=new Date().toISOString();const rec={projectNumber:p,portalId,recipientEmail:email,status:'Active',expiresAt,requireEmailVerification,createdAt:now,revokedAt:null,lastAccessedAt:null,lastVerifiedAt:null};await getStore(PORTAL_STORE).setJSON(`portals/${p}/${portalId}`,rec,{onlyIfNew:true});const token=createEngagementToken({secret:process.env.CONVERA_ENGAGEMENT_TOKEN_SECRET||'',kind:'project_portal',recordId:portalId,projectNumber:p,recipientEmail:email,expiresAt});const base=String(process.env.PUBLIC_SITE_URL||process.env.URL||'https://converastrategies.com').replace(/\/$/,'');const url=`${base}/project/?access=${encodeURIComponent(token)}`;const verificationLine=requireEmailVerification?'\n\nWhen you open the portal, Convera will email a one-time verification code to this address.':'';const emailSent=b?.sendEmail===false?false:await sendEmail(email,`[${p}] Secure Convera project portal`,`Your secure Convera Strategies project portal is ready.\n\nProject: ${p}${project.workingTitle?` — ${project.workingTitle}`:''}\n\nPortal: ${url}\n\nThis link expires ${expiresAt}. Do not forward it.${verificationLine}\n\nConvera Strategies`);await logActivity(p,'client_portal_created',`${portalId} created for client portal access.`,{portalId,expiresAt,requireEmailVerification});return json({ok:true,portal:rec,clientUrl:url,emailSent},201)}
async function updatePortal(req){let b;try{b=await req.json()}catch{return json({error:'Invalid JSON request body.'},400)}const p=cleanText(b?.projectNumber,80).toUpperCase(),id=cleanText(b?.portalId,100).toUpperCase();if(!validProjectNumber(p)||!validPortalId(id))return json({error:'Valid Project # and portal ID required.'},400);const store=getStore(PORTAL_STORE),key=`portals/${p}/${id}`,cur=await store.get(key,{type:'json'});if(!cur)return json({error:'Portal record not found.'},404);const action=cleanText(b?.action,40).toLowerCase(),now=new Date().toISOString();let next;if(action==='revoke')next={...cur,status:'Revoked',revokedAt:now,updatedAt:now};else if(action==='set_verification')next={...cur,requireEmailVerification:Boolean(b.requireEmailVerification),updatedAt:now};else return json({error:'Unsupported portal action.'},400);await store.setJSON(key,next);await logActivity(p,action==='revoke'?'client_portal_revoked':'client_portal_security_updated',action==='revoke'?`${id} revoked.`:`${id} email verification ${next.requireEmailVerification?'enabled':'disabled'}.`,{portalId:id,requireEmailVerification:next.requireEmailVerification});return json({ok:true,portal:next})}
async function sendEmail(to,subject,text){const key=process.env.RESEND_API_KEY,from=process.env.CONVERA_FROM_EMAIL;if(!key||!from)return false;try{const r=await fetch(RESEND_ENDPOINT,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[to],subject,text})});return r.ok}catch{return false}}
