import { getStore } from '@netlify/blobs';
import { createEngagementToken } from './_shared/engagement-token.mjs';
import { INVOICE_STORE, PAYMENT_STORE, INVOICE_STATUSES, INVOICE_TYPES, PAYMENT_TYPES, authorizeOperator, canIssueInvoice, cleanText, getProject, json, listPayments, logActivity, money, normalizeEmail, paymentTotals, publicInvoice, randomHex, refreshInvoiceStatus, round, updateProject, validInvoiceId, validProjectNumber, validateLineItems } from './_shared/billing-admin.mjs';
import { listRecords } from './_shared/engagement-admin.mjs';

const RESEND_ENDPOINT='https://api.resend.com/emails';
export default async function handler(req){
  if(!authorizeOperator(req))return json({error:'Unauthorized.'},401);
  if(req.method==='GET')return list(req);
  if(req.method==='POST')return create(req);
  if(req.method==='PATCH')return update(req);
  return json({error:'Method not allowed.'},405,{Allow:'GET, POST, PATCH'});
}
async function list(req){
  const u=new URL(req.url),p=cleanText(u.searchParams.get('projectNumber'),80).toUpperCase(); if(!validProjectNumber(p))return json({error:'Valid Project # required.'},400);
  const rows=await listRecords(INVOICE_STORE,`invoices/${p}/`); for(let i=0;i<rows.length;i++)rows[i]=await refreshInvoiceStatus(p,rows[i].invoiceId);
  rows.sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt));
  const payments=await listPayments(p); return json({ok:true,invoiceStatuses:INVOICE_STATUSES,invoiceTypes:INVOICE_TYPES,paymentTypes:PAYMENT_TYPES,invoices:rows.map(adminInvoice),payments});
}
async function create(req){
  let b;try{b=await req.json()}catch{return json({error:'Invalid JSON request body.'},400)}
  const p=cleanText(b?.projectNumber,80).toUpperCase(); if(!validProjectNumber(p))return json({error:'Invalid Project #.'},400); const project=await getProject(p); if(!project)return json({error:'Project not found.'},404);
  const eligible=await canIssueInvoice(p); if(!eligible.ok)return json({error:'A signed Project Agreement is required before issuing an invoice.'},409);
  const line=validateLineItems(b?.lineItems); if(line.error)return json({error:line.error},400);
  const invoiceType=cleanText(b?.invoiceType,30); if(!INVOICE_TYPES.includes(invoiceType))return json({error:'Invalid invoice type.'},400);
  const existing=await listRecords(INVOICE_STORE,`invoices/${p}/`); const version=Math.max(0,...existing.map(r=>Number(r.sequence)||0))+1; const invoiceId=`INV-${p.split('-').pop()}-${String(version).padStart(2,'0')}`;
  const tax=money(b?.taxAmount??0); if(tax===null)return json({error:'Tax amount must be zero or greater.'},400); const adjustment=Number(b?.adjustmentAmount??0); if(!Number.isFinite(adjustment)||Math.abs(adjustment)>100000000)return json({error:'Invalid adjustment amount.'},400);
  const total=round(line.subtotal+tax+adjustment); if(total<=0)return json({error:'Invoice total must be greater than zero.'},400);
  const email=normalizeEmail(b?.clientEmail||project.email); if(!/^\S+@\S+\.\S+$/.test(email))return json({error:'Valid client email required.'},400);
  const now=new Date().toISOString(); const record={projectNumber:p,invoiceId,sequence:version,invoiceType,status:'Draft',title:cleanText(b?.title,180)||`${invoiceType} Invoice`,clientName:cleanText(b?.clientName,150)||project.name||'',clientOrganization:cleanText(b?.clientOrganization,180)||project.organization||'',clientEmail:email,agreementId:eligible.agreement.agreementId,issueDate:cleanText(b?.issueDate,30)||now.slice(0,10),dueDate:cleanText(b?.dueDate,30),currency:(cleanText(b?.currency,8)||'USD').toUpperCase(),lineItems:line.items,subtotal:line.subtotal,taxAmount:tax,adjustmentAmount:round(adjustment),total,paidAmount:0,balanceDue:total,paymentTerms:cleanText(b?.paymentTerms,5000),paymentInstructions:cleanText(b?.paymentInstructions,5000),hostedPaymentUrl:cleanText(b?.hostedPaymentUrl,2000),externalInvoiceReference:cleanText(b?.externalInvoiceReference,500),internalNotes:cleanText(b?.internalNotes,5000),createdAt:now,updatedAt:now,sentAt:null,viewedAt:null,publicTokenExpiresAt:null};
  const store=getStore(INVOICE_STORE); const saved=await store.setJSON(`invoices/${p}/${invoiceId}`,record,{onlyIfNew:true}); if(!saved.modified)return json({error:'Invoice collision. Please retry.'},409);
  await updateProject(p,{lastInvoiceId:invoiceId,lastInvoiceStatus:'Draft',outstandingBalance:total,nextAction:`Review ${invoiceId} before sending.`}); await logActivity(p,'invoice_created',`${invoiceId} created for ${record.currency} ${record.total.toFixed(2)}.`,{invoiceId,invoiceType,total:record.total});
  return json({ok:true,invoice:adminInvoice(record)},201);
}
async function update(req){
  let b;try{b=await req.json()}catch{return json({error:'Invalid JSON request body.'},400)} const p=cleanText(b?.projectNumber,80).toUpperCase(),id=cleanText(b?.invoiceId,100).toUpperCase(); if(!validProjectNumber(p)||!validInvoiceId(id))return json({error:'Valid Project # and Invoice ID required.'},400);
  const store=getStore(INVOICE_STORE),key=`invoices/${p}/${id}`,cur=await store.get(key,{type:'json'}); if(!cur)return json({error:'Invoice not found.'},404); const action=cleanText(b?.action,40).toLowerCase();
  if(action==='send')return sendInvoice(cur,key,store,b);
  if(action==='record_payment')return recordPayment(cur,b);
  if(action==='void'){if(cur.status==='Paid')return json({error:'Paid invoices cannot be voided; record a refund or accounting adjustment externally.'},409);const next={...cur,status:'Void',updatedAt:new Date().toISOString()};await store.setJSON(key,next);await updateProject(p,{lastInvoiceStatus:'Void'});await logActivity(p,'invoice_voided',`${id} voided.`,{invoiceId:id});return json({ok:true,invoice:adminInvoice(next)})}
  if(action==='write_off'){if(cur.status==='Paid')return json({error:'Paid invoice cannot be written off.'},409);const next={...cur,status:'Written Off',updatedAt:new Date().toISOString()};await store.setJSON(key,next);await updateProject(p,{lastInvoiceStatus:'Written Off'});await logActivity(p,'invoice_written_off',`${id} marked Written Off.`,{invoiceId:id});return json({ok:true,invoice:adminInvoice(next)})}
  if(cur.status!=='Draft')return json({error:'Only Draft invoices can be edited. Create a replacement invoice if commercial terms change after sending.'},409);
  const line=b.lineItems?validateLineItems(b.lineItems):{items:cur.lineItems,subtotal:cur.subtotal}; if(line.error)return json({error:line.error},400); const tax=b.taxAmount!==undefined?money(b.taxAmount):cur.taxAmount; if(tax===null)return json({error:'Invalid tax amount.'},400); const adjustment=b.adjustmentAmount!==undefined?Number(b.adjustmentAmount):cur.adjustmentAmount; if(!Number.isFinite(adjustment))return json({error:'Invalid adjustment amount.'},400); const total=round(line.subtotal+tax+adjustment); if(total<=0)return json({error:'Invoice total must be greater than zero.'},400);
  const next={...cur,title:b.title!==undefined?cleanText(b.title,180):cur.title,dueDate:b.dueDate!==undefined?cleanText(b.dueDate,30):cur.dueDate,lineItems:line.items,subtotal:line.subtotal,taxAmount:tax,adjustmentAmount:round(adjustment),total,balanceDue:total,paymentTerms:b.paymentTerms!==undefined?cleanText(b.paymentTerms,5000):cur.paymentTerms,paymentInstructions:b.paymentInstructions!==undefined?cleanText(b.paymentInstructions,5000):cur.paymentInstructions,hostedPaymentUrl:b.hostedPaymentUrl!==undefined?cleanText(b.hostedPaymentUrl,2000):cur.hostedPaymentUrl,externalInvoiceReference:b.externalInvoiceReference!==undefined?cleanText(b.externalInvoiceReference,500):cur.externalInvoiceReference,internalNotes:b.internalNotes!==undefined?cleanText(b.internalNotes,5000):cur.internalNotes,updatedAt:new Date().toISOString()}; await store.setJSON(key,next); await updateProject(p,{outstandingBalance:total}); return json({ok:true,invoice:adminInvoice(next)});
}
async function sendInvoice(cur,key,store,b){
  if(!['Draft','Overdue'].includes(cur.status))return json({error:'Only Draft or Overdue invoices may be sent/re-sent.'},409); const secret=process.env.CONVERA_ENGAGEMENT_TOKEN_SECRET||'',base=(process.env.PUBLIC_SITE_URL||'').replace(/\/$/,''); if(!base)return json({error:'PUBLIC_SITE_URL is not configured.'},503); const days=Math.min(90,Math.max(1,Number(b?.expiresDays||30))); const expires=new Date(Date.now()+days*86400000).toISOString(); const token=createEngagementToken({secret,kind:'invoice',recordId:cur.invoiceId,projectNumber:cur.projectNumber,recipientEmail:cur.clientEmail,expiresAt:expires}); const url=`${base}/invoice/?token=${encodeURIComponent(token)}`; const now=new Date().toISOString(); const next={...cur,status:cur.status==='Overdue'?'Overdue':'Sent',sentAt:cur.sentAt||now,updatedAt:now,publicTokenExpiresAt:expires}; await store.setJSON(key,next); await updateProject(cur.projectNumber,{lastInvoiceStatus:next.status,nextAction:`Monitor ${cur.invoiceId} for payment.`}); await logActivity(cur.projectNumber,'invoice_sent',`${cur.invoiceId} sent to client.`,{invoiceId:cur.invoiceId,total:cur.total});
  const sent=await sendEmail(cur.clientEmail,`[${cur.projectNumber}] ${cur.invoiceId} — ${cur.title}`,`Hello ${cur.clientName||''},\n\nConvera Strategies has prepared ${cur.invoiceId} for ${cur.projectNumber}.\n\nReview invoice: ${url}\n\nBalance due: ${cur.currency} ${Number(cur.balanceDue??cur.total).toFixed(2)}\n${cur.dueDate?`Due date: ${cur.dueDate}\n`:''}\nRegards,\nConvera Strategies`); return json({ok:true,invoice:adminInvoice(next),clientUrl:url,emailSent:sent});
}
async function recordPayment(cur,b){
  if(['Void','Written Off'].includes(cur.status))return json({error:'Payments cannot be recorded against a void or written-off invoice.'},409); const type=cleanText(b?.paymentType,20)||'Payment'; if(!PAYMENT_TYPES.includes(type))return json({error:'Invalid payment type.'},400); const amount=money(b?.amount); if(amount===null||amount<=0)return json({error:'Payment/refund amount must be greater than zero.'},400); const paymentId=`PAY-${cur.projectNumber.split('-').pop()}-${randomHex(4)}`,now=new Date().toISOString(); const record={projectNumber:cur.projectNumber,invoiceId:cur.invoiceId,paymentId,type,amount,currency:cur.currency,receivedAt:cleanText(b?.receivedAt,50)||now,paymentMethod:cleanText(b?.paymentMethod,100),reference:cleanText(b?.reference,500),processorFees:money(b?.processorFees??0)||0,note:cleanText(b?.note,2000),createdAt:now}; const pstore=getStore(PAYMENT_STORE); await pstore.setJSON(`payments/${cur.projectNumber}/${cur.invoiceId}/${paymentId}`,record,{onlyIfNew:true}); const next=await refreshInvoiceStatus(cur.projectNumber,cur.invoiceId); await logActivity(cur.projectNumber,type==='Refund'?'refund_recorded':'payment_recorded',`${type} ${paymentId} recorded against ${cur.invoiceId}: ${cur.currency} ${amount.toFixed(2)}.`,{invoiceId:cur.invoiceId,paymentId,type,amount}); return json({ok:true,payment:record,invoice:adminInvoice(next),totals:await paymentTotals(cur.projectNumber,cur.invoiceId)});
}
async function sendEmail(to,subject,text){const key=process.env.RESEND_API_KEY,from=process.env.CONVERA_FROM_EMAIL;if(!key||!from)return false;try{const r=await fetch(RESEND_ENDPOINT,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[to],subject,text})});return r.ok}catch{return false}}
function adminInvoice(r){return {...publicInvoice(r),clientEmail:r.clientEmail,agreementId:r.agreementId,internalNotes:r.internalNotes||'',createdAt:r.createdAt,updatedAt:r.updatedAt,publicTokenExpiresAt:r.publicTokenExpiresAt||null};}
