import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const pkg=JSON.parse(read('package.json'));
const ver=JSON.parse(read('VERSION.json'));
const header=read('src/components/SiteHeader.astro');
const home=read('src/styles/home.css');
const services=read('src/pages/services.astro');
const readme=read('README.md');
const manifest=read('RELEASE-MANIFEST.md');
const checks=[];
const add=(label,ok)=>checks.push({label,ok:Boolean(ok)});
add('package version is 2.54.0',pkg.version==='2.54.0');
add('VERSION metadata is 2.54.0',ver.version==='2.54.0');
add('header has narrower-desktop calibration',header.includes('@media (min-width: 821px) and (max-width: 1080px)')&&header.includes('grid-template-columns: minmax(170px'));
add('desktop navigation remains active above 820px',header.includes('@media (max-width: 820px)')&&header.includes('.desktop-nav { display: none; }'));
add('Home has intermediate desktop calibration',home.includes('@media (min-width: 821px) and (max-width: 1080px)')&&home.includes('grid-template-columns: minmax(0, .98fr) minmax(360px, 1.02fr)'));
add('Home headline remains two-line desktop composition',home.includes('.home-hero__copy h1 span { display: block; white-space: nowrap; }'));
add('Home feature rows remain two columns at intermediate widths',home.includes('grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);'));
add('Areas of Inquiry contracts proportionally rather than restacking',home.includes('.home-inquiry-item strong { font-size: clamp(20px, 2.15vw, 24px); }'));
add('Services images reserve intrinsic dimensions',services.includes('width="1200" height="675"'));
add('public-safety image has local fallback',services.includes("this.src='/images/editorial/convera-institution-systems.svg'"));
add('README points to current verification script',readme.includes('npm run verify:2.54'));
add('Manifest identifies current stage and verification',manifest.includes('Fluid Desktop Composition Hardening Candidate')&&manifest.includes('dedicated 2.54 verification controls'));
const failed=checks.filter(c=>!c.ok);
for(const c of checks) console.log(`${c.ok?'PASS':'FAIL'} ${c.label}`);
console.log(`\n${checks.length-failed.length}/${checks.length} 2.54 checks passed.`);
if(failed.length) process.exit(1);
