import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const exists=(p)=>fs.existsSync(path.join(root,p));
const pkg=JSON.parse(read('package.json'));
const ver=JSON.parse(read('VERSION.json'));
const header=read('src/components/SiteHeader.astro');
const home=read('src/pages/index.astro');
const homeCss=read('src/styles/home.css');
const services=read('src/pages/services.astro');
const readme=read('README.md');
const manifest=read('RELEASE-MANIFEST.md');
const publications=read('src/config/publications.ts');
const talk=read('src/content/blog/talk-is-cheap-and-getting-cheaper.md');
const checks=[];
const add=(label,ok)=>checks.push({label,ok:Boolean(ok)});
add('package version is 2.55.0',pkg.version==='2.55.0');
add('VERSION metadata is 2.55.0',ver.version==='2.55.0');
add('2.54 narrower-desktop header calibration is preserved',header.includes('@media (min-width: 821px) and (max-width: 1080px)')&&header.includes('grid-template-columns: minmax(170px'));
add('desktop navigation remains active above 820px',header.includes('@media (max-width: 820px)')&&header.includes('.desktop-nav { display: none; }'));
add('2.54 Home intermediate desktop calibration is preserved',homeCss.includes('@media (min-width: 821px) and (max-width: 1080px)')&&homeCss.includes('grid-template-columns: minmax(0, .98fr) minmax(360px, 1.02fr)'));
add('Home feature rows remain two columns at intermediate widths',homeCss.includes('grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);'));
add('Services image safety baseline is preserved',services.includes('width="1200" height="675"')&&services.includes("this.src='/images/editorial/convera-institution-systems.svg'"));
add('Home Featured Publication uses supplied artwork',home.includes('src="/images/home/an_objective_strategy.png"'));
add('Home Featured Essay uses supplied artwork',home.includes('src="/images/home/talk_is_cheap.png"'));
add('supplied Featured Publication artwork exists',exists('public/images/home/an_objective_strategy.png'));
add('supplied Featured Essay artwork exists',exists('public/images/home/talk_is_cheap.png'));
add('publication record artwork remains unchanged',publications.includes("image: '/images/publications/publication-objective-strategy.jpg'"));
add('blog article artwork remains unchanged',talk.includes('image: "/images/blog/talk-is-cheap.jpg"'));
add('README points to current verification script',readme.includes('npm run verify:2.55'));
add('Manifest identifies current stage and verification',manifest.includes('Landing Editorial Image Refresh Candidate')&&manifest.includes('dedicated 2.55 verification controls'));
const failed=checks.filter(c=>!c.ok);
for(const c of checks) console.log(`${c.ok?'PASS':'FAIL'} ${c.label}`);
console.log(`\n${checks.length-failed.length}/${checks.length} 2.55 checks passed.`);
if(failed.length) process.exit(1);
