import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const checks=[];
const add=(label,ok)=>checks.push({label,ok:Boolean(ok)});
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const pkg=JSON.parse(read('package.json'));
const ver=JSON.parse(read('VERSION.json'));
const home=read('src/pages/index.astro');
const mission=read('src/pages/mission.astro');
const support=read('src/pages/support.astro');
const header=read('src/components/SiteHeader.astro');
const envExample=read('.env.example');
const opsExample=read('.env.operations.example');
const formNotes=read('FORM-NOTIFICATIONS.md');
const releaseVerification=read('RELEASE-VERIFICATION.md');
const currentDocs=['ACTIVATION-CHECKLIST.md','ACTIVATION-STATUS.md','CLIENT-INTAKE-DASHBOARD.md','DEPLOY-NOW.md','DEPLOYMENT-EXECUTION.md','ENVIRONMENT-MAP.md','EXTERNAL-ACTIVATION.md','FORM-NOTIFICATIONS.md','LAUNCH-ACTIVATION.md','LAUNCH-CHECKLIST.md','LAUNCH-NOW.md','NEXT-ACTIONS.md','OPERATIONS.md','OPERATOR-CONSOLE.md','RELEASE-VERIFICATION.md'];
const docsText=currentDocs.map(read).join('\n');
add('package version is 2.51.0',pkg.version==='2.51.0');
add('VERSION metadata is 2.51.0',ver.version==='2.51.0');
add('Home strengthens rather than protects institutions',home.includes('strengthen the institutions that make a healthier, more hopeful future possible')&&!home.includes('protect the institutions that make a healthier, more hopeful future possible'));
add('Mission strengthens rather than protects institutions',mission.includes('strengthen the institutions that make a healthier, more hopeful future possible')&&!mission.includes('protect the institutions that make a healthier, more hopeful future possible'));
add('Home support kicker is work-centered',home.includes('<p class="home-kicker">Support the Work</p>'));
add('Home support heading emphasizes reach',home.includes('<h2>Help the Work Travel Farther</h2>'));
add('Support metadata foregrounds independent public work',support.includes('Support Ryan Brown’s independent publications, speaking, public engagement, and work advancing thoughtful institutional change.'));
add('Support notice describes broader reach of ideas',support.includes('the broader reach of ideas associated with Convera Strategies'));
add('approved slogan remains clean in header',header.includes('{site.tagline}')&&!header.includes('.site-brand__tagline::before')&&!header.includes('.site-brand__tagline::after'));
add('public environment template restored',envExample.includes('PUBLIC_SUPPORT_ONE_TIME_URL=')&&envExample.includes('PUBLIC_SUPPORT_MONTHLY_URL=')&&envExample.includes('PUBLIC_PLAUSIBLE_DOMAIN='));
add('operational environment template restored',opsExample.includes('OPS_RYAN_MAIL_VERIFIED=false')&&opsExample.includes('OPS_SUPPORT_FLOW_VERIFIED=false')&&opsExample.includes('OPS_MOBILE_QA_VERIFIED=false'));
add('current docs do not describe Intake as direct/shareable public entry',!/direct prospective-client|shareable prospective-client|direct client intake|direct Client Intake/i.test(docsText));
add('form documentation matches current public/private forms',formNotes.includes('website-contact')&&formNotes.includes('follow-the-work')&&formNotes.includes('client-intake')&&!formNotes.includes('`work-with-convera` — detailed professional inquiry'));
add('release verification describes current private Intake boundary',releaseVerification.includes('Contact → manual review → private Intake invitation')&&!releaseVerification.includes('2.14.0 high-UI'));
const failed=checks.filter(c=>!c.ok);
for(const c of checks) console.log(`${c.ok?'PASS':'FAIL'} ${c.label}`);
console.log(`\n${checks.length-failed.length}/${checks.length} 2.51 checks passed.`);
if(failed.length) process.exit(1);
