import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const checks=[];
const add=(label,ok)=>checks.push({label,ok:Boolean(ok)});
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const pkg=JSON.parse(read('package.json'));
const ver=JSON.parse(read('VERSION.json'));
const globalCss=read('src/styles/global.css');
const layout=read('src/layouts/BaseLayout.astro');
const header=read('src/components/SiteHeader.astro');
const theme=read('src/components/ThemeToggle.astro');
const motion=read('public/assets/convera-motion.js');
const site=read('src/config/site.ts');
add('package version is 2.50.0',pkg.version==='2.50.0');
add('VERSION metadata is 2.50.0',ver.version==='2.50.0');
add('approved slogan remains configured',site.includes("tagline: 'People are what we do.'"));
add('skip link sits above sticky header',/\.skip-link[\s\S]*?z-index:\s*2000/.test(globalCss));
add('Google Fonts requests display swap',layout.includes('&display=swap'));
add('mobile menu uses state-safe label',header.includes('aria-label="Navigation menu"'));
add('mobile menu closes after navigation',header.includes('menu.open = false'));
add('theme storage write is guarded',theme.includes("try { localStorage.setItem('convera-theme', next); } catch {}"));
add('obsolete home hero quote motion selector removed',!motion.includes("'.home-hero__quote'"));
add('header slogan still has no decorative rules',!header.includes('.site-brand__tagline::before')&&!header.includes('.site-brand__tagline::after'));
const failed=checks.filter(c=>!c.ok);
for(const c of checks) console.log(`${c.ok?'PASS':'FAIL'} ${c.label}`);
console.log(`\n${checks.length-failed.length}/${checks.length} 2.50 checks passed.`);
if(failed.length) process.exit(1);
