import fs from 'node:fs';import path from 'node:path';import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const checks=[];const text=p=>fs.readFileSync(path.join(root,p),'utf8');const ok=(n,c)=>checks.push([n,Boolean(c)]);
const token=text('netlify/functions/_shared/engagement-token.mjs'),admin=text('netlify/functions/_shared/command-center-admin.mjs'),portal=text('netlify/functions/project-portal.mjs'),client=text('netlify/functions/client-project-portal.mjs'),cmd=text('netlify/functions/project-command.mjs'),ms=text('netlify/functions/project-milestones.mjs'),rem=text('netlify/functions/project-reminders.mjs'),close=text('netlify/functions/project-closeout.mjs'),op=text('public/operator/project.html'),cp=text('public/project/index.html'),registry=text('public/operator/projects.html'),docs=text('docs/COMMAND-CENTER-CLIENT-PORTAL.md');
ok('Portal token kind enabled',token.includes("'project_portal'"));
ok('Portal records revocable',portal.includes("status:'Revoked'")&&client.includes("portal.status!=='Active'"));
ok('Portal token is email-record bound',client.includes('portal.recipientEmail!==check.payload.recipientEmail'));
ok('Portal expiration enforced',client.includes('Date.parse(portal.expiresAt)<=Date.now()'));
ok('Client snapshot filters internal documents',admin.includes("d.visibility==='client'"));
ok('Client snapshot excludes internal agreement terms',!admin.match(/approvedTerms:agreement|internalNotes:agreement/));
ok('External URLs restricted to http/https',admin.includes("['https:','http:'].includes(u.protocol)"));
ok('Command center operator auth',cmd.includes('authorizeOperator(req)'));
ok('Command center page links core modules',op.includes('billing.html')&&op.includes('documents.html')&&op.includes('agreement.html'));
ok('Registry links Command Center',registry.includes('/operator/project.html?project='));
ok('Milestone reminders require client visibility',ms.includes('!m.clientVisible')||ms.includes('clientVisible'));
ok('Automatic reminders opt-in',rem.includes('project.autoMilestoneReminders')&&rem.includes('project.autoInvoiceReminders'));
ok('Reminder deduplication store',rem.includes('REMINDER_STORE')&&rem.includes('eventKey'));
ok('Scheduled daily reminder configured',rem.includes("schedule:'0 14 * * *'"));
ok('Weekend suppression uses New York timezone',rem.includes("timeZone:'America/New_York'")&&rem.includes("ny.weekday==='Sat'"));
ok('Invoice reminder uses invoice billing email',rem.includes('inv.clientEmail||email'));
ok('Retention review does not delete records',docs.includes('No automatic deletion is performed')&&!rem.match(/\.delete\(|delete\(/));
ok('Closeout supports legal hold',close.includes('legalHold'));
ok('Archive synchronizes project status',close.includes("status:'Archived'"));
ok('Client deliverable acknowledgment is not release language',docs.includes('does not create a release'));
ok('Final acknowledgment updates closeout checklist',client.includes('clientAcknowledgmentResolved:true'));
ok('Client portal offers project-visible documents',cp.includes('&download=')&&client.includes("meta.visibility!=='client'"));
ok('Reminder automation disabled by default in docs',docs.includes('off by default'));
ok('HubSpot Deals absent',![portal,client,cmd,ms,rem,close].join('\n').match(/hubspot.*deal|deal.*hubspot/i));
for(const [n,v] of checks)console.log(`${v?'PASS':'FAIL'}  ${n}`);const failed=checks.filter(x=>!x[1]);console.log(`\n${checks.length-failed.length}/${checks.length} checks passed.`);if(failed.length)process.exit(1);
