import fs from 'node:fs'; import path from 'node:path';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const checks=[];const text=p=>fs.readFileSync(path.join(root,p),'utf8');const ok=(name,cond)=>checks.push([name,Boolean(cond)]);
const billing=text('netlify/functions/project-billing.mjs'),docs=text('netlify/functions/project-documents.mjs'),clientDocs=text('netlify/functions/client-documents.mjs'),token=text('netlify/functions/_shared/engagement-token.mjs'),helper=text('netlify/functions/_shared/billing-admin.mjs'),registry=text('public/operator/projects.html'),install=text('docs/BILLING-AND-DOCUMENTS.md');
ok('Invoice requires signed agreement',billing.includes('signed Project Agreement is required'));
ok('No card credential collection',!billing.match(/cardNumber|cvv|routingNumber|bankAccount/i));
ok('Deposit gate sync',helper.includes('depositStatus:\'Paid\'')&&helper.includes('computeReadiness'));
ok('Partial payment support',helper.includes("'Partially Paid'"));
ok('Refund ledger support',helper.includes("'Refund'"));
ok('Invoice secure token kind',token.includes("'invoice'"));
ok('Document request secure token kind',token.includes("'document_request'"));
ok('Document share secure token kind',token.includes("'document_share'"));
ok('Native document cap 4MB',helper.includes('4 * 1024 * 1024'));
ok('Document MIME allow-list',helper.includes('application/pdf')&&helper.includes('wordprocessingml'));
ok('Client upload email bound',clientDocs.includes("email!==check.payload.recipientEmail"));
ok('Client download requires client visibility',clientDocs.includes("meta.visibility!=='client'"));
ok('Operator function auth',docs.includes('authorizeOperator(req)'));
ok('External secure upload supported',docs.includes("uploadMode")&&docs.includes("externalUploadUrl"));
ok('Registry links billing/documents',registry.includes('/operator/billing.html')&&registry.includes('/operator/documents.html'));
ok('Security boundary documented',install.includes('does not provide malware scanning')&&install.includes('regulated-data compliance'));
ok('HubSpot Deals absent',![billing,docs,clientDocs].join('\n').match(/hubspot.*deal|deal.*hubspot/i));
for(const [n,v] of checks)console.log(`${v?'PASS':'FAIL'}  ${n}`);const failed=checks.filter(x=>!x[1]);console.log(`\n${checks.length-failed.length}/${checks.length} checks passed.`);if(failed.length)process.exit(1);
