import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const pkg=JSON.parse(read('package.json'));
const ver=JSON.parse(read('VERSION.json'));
const home=read('src/pages/index.astro');
const mission=read('src/pages/mission.astro');
const base=read('src/layouts/BaseLayout.astro');
const header=read('src/components/SiteHeader.astro');
const checks=[];
const add=(label,ok)=>checks.push({label,ok:Boolean(ok)});
add('package version is 2.52.0',pkg.version==='2.52.0');
add('VERSION metadata is 2.52.0',ver.version==='2.52.0');
add('Home lead uses institutional-change framing',home.includes('approach institutional change with greater perspective and purpose'));
add('Home lead avoids duplicate strengthen phrasing',!home.includes('strengthen workplace culture, and strengthen'));
add('Mission lead uses institutional-change framing',mission.includes('approach institutional change with greater perspective and purpose'));
add('Mission quote says strengthening institutions',mission.includes('“Strengthening institutions is an investment in the future people hope to build.”'));
add('Mission avoids protecting-institutions construction',!mission.includes('Protecting institutions does not mean protecting every existing practice'));
add('Mission emphasizes adaptation without preserving every practice',mission.includes('Strengthening institutions does not require preserving every existing practice.'));
add('Google Fonts request has one display swap',base.includes('&display=swap" rel="stylesheet"')&&!base.includes('display=swap&display=swap'));
add('approved slogan remains clean in header',header.includes('{site.tagline}')&&!header.includes('.site-brand__tagline::before')&&!header.includes('.site-brand__tagline::after'));
const failed=checks.filter(c=>!c.ok);
for(const c of checks) console.log(`${c.ok?'PASS':'FAIL'} ${c.label}`);
console.log(`\n${checks.length-failed.length}/${checks.length} 2.52 checks passed.`);
if(failed.length) process.exit(1);
