import fs from 'node:fs';
import path from 'node:path';
const root = process.cwd();
const checks = [];
const add = (label, ok) => checks.push({label, ok:Boolean(ok)});
const read = p => fs.readFileSync(path.join(root,p),'utf8');
const pkg = JSON.parse(read('package.json'));
const ver = JSON.parse(read('VERSION.json'));
const header = read('src/components/SiteHeader.astro');
const site = read('src/config/site.ts');
const footer = read('src/components/SiteFooter.astro');
add('package version is 2.49.0', pkg.version === '2.49.0');
add('VERSION metadata is 2.49.0', ver.version === '2.49.0');
add('approved slogan remains configured', site.includes("tagline: 'People are what we do.'"));
add('header renders slogan in brand lockup', header.includes('site-brand__tagline') && header.includes('{site.tagline}'));
add('slogan keeps italic editorial treatment', header.includes('font-style: italic'));
add('slogan has no decorative before rule', !header.includes('.site-brand__tagline::before'));
add('slogan has no decorative after rule', !header.includes('.site-brand__tagline::after'));
add('footer does not repeat slogan', !footer.includes('{site.tagline}'));
const failed = checks.filter(c => !c.ok);
for (const c of checks) console.log(`${c.ok?'PASS':'FAIL'} ${c.label}`);
console.log(`\n${checks.length-failed.length}/${checks.length} 2.49 checks passed.`);
if (failed.length) process.exit(1);
