import fs from 'node:fs';
import path from 'node:path';
const root = process.cwd();
const checks = [];
const add = (label, ok) => checks.push({label, ok:Boolean(ok)});
const read = p => fs.readFileSync(path.join(root,p),'utf8');
const pkg = JSON.parse(read('package.json'));
const ver = JSON.parse(read('VERSION.json'));
const supportPanel = read('src/components/shared/SupportPanel.astro');
const commercial = read('src/components/shared/CommercialCTA.astro');
const services = read('src/config/services.ts');
const mission = read('src/pages/mission.astro');
const contact = read('src/pages/contact.astro');
const work = read('src/pages/work-with-convera.astro');
const header = read('src/components/SiteHeader.astro');
const footer = read('src/components/SiteFooter.astro');
add('package version is 2.48.0', pkg.version === '2.48.0');
add('VERSION metadata is 2.48.0', ver.version === '2.48.0');
add('shared Support panel uses reach message', supportPanel.includes('Help necessary ideas travel farther.') && supportPanel.includes('greater room to write, speak'));
add('shared Support panel no longer uses old generic progress line', !supportPanel.includes('People · Progress · A stronger tomorrow.'));
add('commercial CTA uses question language', commercial.includes('clearer view of the question') && commercial.includes('questions, decisions, or situations'));
add('commercial CTA removes challenge framing', !/\bchallenges?\b/i.test(commercial));
add('service descriptions remove challenge framing', !/\bchallenges?\b/i.test(services));
add('mission uses complex questions', mission.includes('navigate complex questions'));
add('contact remains public professional entry point', contact.includes('use this Contact form first') && contact.includes('separate Intake invitation'));
add('work page preserves manual private Intake flow', work.includes('separate private Intake invitation is sent manually') && work.includes('Intake is not public'));
add('header retains approved slogan lockup', header.includes('site-brand__tagline') && header.includes('{site.tagline}'));
add('footer does not repeat approved slogan', !footer.includes('{site.tagline}'));
const failed = checks.filter(c=>!c.ok);
for (const c of checks) console.log(`${c.ok?'PASS':'FAIL'} ${c.label}`);
console.log(`\n${checks.length-failed.length}/${checks.length} 2.48 checks passed.`);
if (failed.length) process.exit(1);
