import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..'),checks=[];const text=p=>fs.readFileSync(path.join(root,p),'utf8'),ok=(n,c)=>checks.push([n,Boolean(c)]);
const token=text('netlify/functions/_shared/engagement-token.mjs'),sec=text('netlify/functions/_shared/portal-security.mjs'),portal=text('netlify/functions/project-portal.mjs'),client=text('netlify/functions/client-project-portal.mjs'),ops=text('netlify/functions/_shared/operations-intelligence.mjs'),opsFn=text('netlify/functions/project-operations.mjs'),opsPage=text('public/operator/operations.html'),clientPage=text('public/project/index.html'),registry=text('netlify/functions/project-registry.mjs'),registryPage=text('public/operator/projects.html'),cmd=text('netlify/functions/project-command.mjs'),cmdPage=text('public/operator/project.html'),docs=text('docs/OPERATIONS-INTELLIGENCE-PORTAL-SECURITY.md'),env=text('.env.operations-security.example');
ok('Portal session token kind enabled',token.includes("'project_portal_session'"));
ok('Portal verification defaults on',portal.includes("CONVERA_PORTAL_REQUIRE_EMAIL_VERIFICATION||'true'"));
ok('OTP codes generated server side',sec.includes('randomInt(0,1000000)'));
ok('OTP plaintext not stored',sec.includes('codeHash:codeHash')&&!sec.match(/code:\s*code[,}]/));
ok('OTP uses HMAC hashing',sec.includes("createHmac('sha256'"));
ok('OTP throttling exists',sec.includes('otpCooldownMs'));
ok('OTP repeated-attempt lockout exists',sec.includes('lockUntil')&&sec.includes('maxAttempts'));
ok('OTP expires',sec.includes('codeExpiresAt'));
ok('Client data blocked before verification',client.includes('verificationRequired:true')&&client.includes("portal.requireEmailVerification&&!session.ok"));
ok('Verified session required for protected portal',client.includes("'x-convera-portal-session'"));
ok('Portal session is short lived',sec.includes('CONVERA_PORTAL_SESSION_HOURS'));
ok('Portal verification email bound',client.includes('c.payload.recipientEmail===portal.recipientEmail'));
ok('Client browser stores verified session only in sessionStorage',clientPage.includes('sessionStorage.setItem'));
ok('Protected document download uses session header',clientPage.includes('downloadDoc')&&clientPage.includes("headers:headers()"));
ok('Operator can require verification per portal',cmdPage.includes('portalVerify')&&portal.includes('requireEmailVerification'));
ok('Operations endpoint operator protected',opsFn.includes('authorizeOperator(req)'));
ok('Operations dashboard exists',opsPage.includes('Operations Intelligence'));
ok('Project status summary exists',ops.includes('statusCounts'));
ok('Project aging summary exists',ops.includes('ageBuckets'));
ok('Source/referral summary exists',ops.includes('sourceCounts'));
ok('Capacity indicator configurable',ops.includes('CONVERA_CAPACITY_UNITS')&&registry.includes('capacityWeight'));
ok('Priority and target completion supported',registry.includes('priority')&&registry.includes('targetCompletionDate'));
ok('Registry UI exposes source/referral fields',registryPage.includes('project-referral')&&registryPage.includes('project-source-detail'));
ok('Command center exposes operations profile',cmdPage.includes('Operations profile')&&cmd.includes('referralSource'));
ok('Billing watch separates administrative ledger language',docs.includes('administrative ledger summaries'));
ok('Portal security inventory identifies legacy links',ops.includes('legacyNoVerificationPortals'));
ok('Verification is not called MFA',docs.includes('not strong multi-factor authentication')||docs.includes('not strong multi-factor'));
ok('Environment template includes separate OTP secret',env.includes('CONVERA_PORTAL_OTP_SECRET'));
ok('HubSpot Deals absent',![sec,portal,client,ops,opsFn,registry,cmd].join('\n').match(/hubspot.*deal|deal.*hubspot/i));
for(const[n,v]of checks)console.log(`${v?'PASS':'FAIL'}  ${n}`);const failed=checks.filter(x=>!x[1]);console.log(`\n${checks.length-failed.length}/${checks.length} checks passed.`);if(failed.length)process.exit(1);
