import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const pkg=JSON.parse(read('package.json'));
const ver=JSON.parse(read('VERSION.json'));
const intake=read('src/pages/intake.astro');
const intakeThanks=read('src/pages/intake/thank-you.astro');
const supportThanks=read('src/pages/support/thank-you.astro');
const notFound=read('src/pages/404.astro');
const mission=read('src/pages/mission.astro');
const about=read('src/pages/about.astro');
const readme=read('README.md');
const manifest=read('RELEASE-MANIFEST.md');
const checks=[];
const add=(label,ok)=>checks.push({label,ok:Boolean(ok)});
add('package version is 2.53.0',pkg.version==='2.53.0');
add('VERSION metadata is 2.53.0',ver.version==='2.53.0');
add('Intake description is private and invitation-based',intake.includes('Private Convera Strategies intake')&&intake.includes('invited after an initial Contact review'));
add('Intake confirmation preserves invited workflow',intakeThanks.includes('Your invited intake has been submitted.'));
add('Support confirmation uses current reach-and-voice message',supportThanks.includes('Your support helps necessary ideas travel farther.')&&supportThanks.includes('greater room to write, speak'));
add('404 uses direct unavailable language',notFound.includes('This page is unavailable.')&&!notFound.includes('found its way forward'));
add('Mission hero avoids repeated investment sentence',mission.includes('institutional change can remain deliberate, useful, and centered on people')&&!mission.includes('approaches problems differently because strengthening institutions is an investment in the future'));
add('About method preserves rather than protects strengths',about.includes('Preserve what is working.')&&!about.includes('Protect what is working.'));
add('README points to current verification script',readme.includes('npm run verify:2.53'));
add('Manifest identifies current stage and verification',manifest.includes('Final Public Flow & Documentation Coherence Candidate')&&manifest.includes('dedicated 2.53 verification controls'));
const failed=checks.filter(c=>!c.ok);
for(const c of checks) console.log(`${c.ok?'PASS':'FAIL'} ${c.label}`);
console.log(`\n${checks.length-failed.length}/${checks.length} 2.53 checks passed.`);
if(failed.length) process.exit(1);
